### ISSUE TITLE
mysql / mysql2::error: failed to open the referenced table

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/uber-demo-app#1]
### 発生したエラー
```
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Failed to open the referenced table 'orders'
/Users/shota/uber-eats-app/db/migrate/20210110061940_create_line_foods.rb:3:in `change'
/Users/shota/uber-eats-app/bin/rails:9:in `<top (required)>'
/Users/shota/uber-eats-app/bin/spring:15:in `require'
/Users/shota/uber-eats-app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Failed to open the referenced table 'orders'
/Users/shota/uber-eats-app/db/migrate/20210110061940_create_line_foods.rb:3:in `change'
/Users/shota/uber-eats-app/bin/rails:9:in `<top (required)>'
/Users/shota/uber-eats-app/bin/spring:15:in `require'
/Users/shota/uber-eats-app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
Mysql2::Error: Failed to open the referenced table 'orders'
/Users/shota/uber-eats-app/db/migrate/20210110061940_create_line_foods.rb:3:in `change'
/Users/shota/uber-eats-app/bin/rails:9:in `<top (required)>'
/Users/shota/uber-eats-app/bin/spring:15:in `require'
/Users/shota/uber-eats-app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### 状況
データベース（MySQL）のテーブルを作成を下記の順で作成：
 - ① db/migrate/yyyymmddhhmmss_create_restaurants.rb
 - ② db/migrate/yyyymmddhhmmss_create_foods.rb
 - ③ db/migrate/yyyymmddhhmmss_create_line_foods.rb
 - ④ db/migrate/yyyymmddhhmmss_create_orders.rb

マイグレーションエラーが発生したLineFoodテーブルのコード：
``` ruby
class CreateLineFoods < ActiveRecord::Migration[6.0]
  def change
    create_table :line_foods do |t|
      t.references :food, null: false, foreign_key: true
      t.references :restaurant, null: false, foreign_key: true
      t.references :order, foreign_key: true
      t.integer :count, null: false, default: 0
      t.boolean :active, null: false, default: false

      t.timestamps
    end
  end
end
```

**Comment by hasyrails** [comment]
### 解決
#### 参考
[MySQL - rails db:migrateができません（おそらくmysqlのカラムがマッチしていない）｜teratail](https://teratail.com/questions/89334#reply-139359)
> t.references :follow, foreign_key: true
としているのに、
関連すべきFollowモデルがないのが原因かと思われます。

> モデルを作成するマイグレーションファイルを作成し、日付該当数字を
20170821114818
にでもすれば、
20170821114819_create_storages.rb
よりも前に実行されます。
#### 原因
``` ruby
class CreateLineFoods < ActiveRecord::Migration[6.0]
  def change
    create_table :line_foods do |t|
      t.references :order, foreign_key: true
    end
  end
end
```

Orderテーブルが作成される前に
CreateLineFoodテーブルで
```t.references :oreder```として参照しようとしているのがエラーの原因

→ migrateの実行順序を変えることでエラー解消成功
